import { useEffect, useState } from "react";
import Editor from "@monaco-editor/react";
import api from "../services/api";

const GlobalCompiler = () => {
  const [languages,setLanguages]=useState([]); const [languageId,setLanguageId]=useState("");
  const [code,setCode]=useState('public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello DevConnect!");\n    }\n}');
  const [stdin,setStdin]=useState(""); const [output,setOutput]=useState(""); const [status,setStatus]=useState(""); const [running,setRunning]=useState(false);
  useEffect(()=>{(async()=>{try{const r=await api.get("/compiler/languages");const list=r.data.languages||r.data||[];setLanguages(list.filter(x=>x?.id!==undefined&&x?.name&&x.is_archived!==true));const java=list.find(x=>x.name?.toLowerCase().includes("java"));if(java)setLanguageId(String(java.id));}catch(e){setStatus(e.response?.data?.message||"Unable to load languages");}})();},[]);
  const monaco=(n="")=>{n=n.toLowerCase();if(n.includes("java"))return"java";if(n.includes("python"))return"python";if(n.includes("javascript"))return"javascript";if(n.includes("typescript"))return"typescript";if(n.includes("c++"))return"cpp";if(n.includes("c#"))return"csharp";return"plaintext";};
  const run=async()=>{if(!code.trim())return setOutput("Write some code first.");if(!languageId)return setOutput("Select a language.");try{setRunning(true);setStatus("Submitting...");setOutput("");const r=await api.post("/compiler/global/run",{sourceCode:code,languageId:Number(languageId),stdin});let result;for(let i=0;i<20;i++){const x=await api.get(`/compiler/global/result/${r.data.token}`);result=x.data;if(![1,2].includes(result.status?.id))break;await new Promise(res=>setTimeout(res,700));}setOutput(result?.stdout||result?.compile_output||result?.stderr||result?.message||result?.status?.description||"No output");setStatus(result?.status?.description||"Finished");}catch(e){setStatus("Execution failed");setOutput(e.response?.data?.message||e.message);}finally{setRunning(false);}};
  const selected=languages.find(x=>String(x.id)===String(languageId));
  return <div className="space-y-4"><div className="flex flex-col justify-between gap-4 rounded-xl border bg-white p-5 md:flex-row md:items-center"><div><h1 className="text-xl font-bold">🌐 Global Compiler</h1><p className="mt-1 text-sm text-slate-500">Test code before posting a DevConnect answer.</p></div><div className="flex gap-3"><select value={languageId} onChange={e=>setLanguageId(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">Select Language</option>{languages.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button onClick={run} disabled={running||!languageId} className="rounded-lg bg-slate-900 px-5 py-2 text-sm font-semibold text-white disabled:opacity-50">{running?"Running...":"▶ Run Code"}</button></div></div>{status&&<div className="rounded-lg border bg-white p-3 text-sm text-slate-500">{status}</div>}<div className="overflow-hidden rounded-xl border"><Editor height="55vh" theme="vs-dark" language={monaco(selected?.name)} value={code} onChange={v=>setCode(v||"")} options={{minimap:{enabled:false},fontSize:14,automaticLayout:true}}/></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-white"><h2 className="border-b p-4 text-sm font-semibold">Standard Input</h2><textarea value={stdin} onChange={e=>setStdin(e.target.value)} className="min-h-32 w-full p-4 font-mono text-sm outline-none" placeholder="Enter input..."/></div><div className="rounded-xl border bg-white"><h2 className="border-b p-4 text-sm font-semibold">Output</h2><pre className="min-h-32 whitespace-pre-wrap bg-slate-950 p-4 font-mono text-sm text-slate-200">{output||"Program output will appear here..."}</pre></div></div></div>;
};
export default GlobalCompiler;
