const express = require("express");
const protect = require("../middleware/authMiddleware");
const { getTasks, createTask, updateTask, deleteTask } = require("../controllers/taskController");
const router = express.Router();
router.use(protect);
router.get("/project/:projectId", getTasks);
router.post("/project/:projectId", createTask);
router.patch("/:id", updateTask);
router.delete("/:id", deleteTask);
module.exports = router;
